#!/bin/bash
sum=0
rows=0
columns=0


while IFS= read -rN1 char; do
    if [[ "$char" == $'\n' ]]; 
        then ((++rows))
    fi
    if [[ "$char" == $'\t' ]]; 
        then ((++columns))
    fi
done < "$1"

columns=$(( $columns / $rows))
((columns++))
echo -e "\"$rows $columns\""

# while read num
# do
#     echo "In loop"
#     echo "num: $num"
#     sum=`expr $sum + $num`
#     echo "sum: $sum"
#     echo -e "End of loop\n"

# done < "$1"

# while IFS= read -r line; do
#     echo "Text read from file: $line"
# done < "$1"


# reference materials:
# https://stackoverflow.com/questions/10929453/read-a-file-line-by-line-assigning-the-value-to-a-variable