compile:
		gcc -g -o tays.buildrooms tays.buildrooms.c
		gcc -g -pthread -o tays.adventure tays.adventure.c

build:
		tays.buildrooms

adventure:
		tays.adventure

clean:
		-rm -f tays.buildrooms
		-rm -f tays.adventure