compile:
		gcc -o tays.buildrooms tays.buildrooms.c
		gcc -o tays.adventure tays.adventure.c

runBuild:
		tays.buildrooms

runAdventure:
		tays.adventure

clean:
		-rm -f tays.buildrooms
		-rm -f tays.adventure